table DimDate
	lineageTag: 90779531-e4d0-4e14-8cb9-11a8f2404263

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34755d2e-f059-4f19-9d40-0baa6ac79472
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 2b9b6238-c81e-4bdb-9f60-600f44efa720
			defaultHierarchy: LocalDateTable_c19b9ce6-a42c-4ba7-8d43-10025cc7d9c1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Name'
		dataType: string
		lineageTag: 13a54d02-4c44-44c5-a9ad-7d9962389a1c
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 95ff0f46-fa9e-4148-953c-4c61074f31ee
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: e92c0e40-7f22-4657-a2d6-21d07500d151
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 6b960a9d-e8f3-4584-873e-4921ca8bb6f0
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: d335c929-1227-4665-8394-f9d8c4d5d10c
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		dataType: string
		lineageTag: f660785c-6fe6-4c54-a3ae-3ed2d04c2cea
		summarizeBy: none
		sourceColumn: Year Quarter
		sortByColumn: QuarterSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column QuarterSort
		dataType: string
		lineageTag: afb14f03-17f6-4193-9bb5-0922f272ada7
		summarizeBy: none
		sourceColumn: QuarterSort

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Regional NM & ACH outputs by te (2)", #"Global DU escalations and escal (2)", #"Global DU wait time buckets (2)", #"Global linking escalations and (2)", #"Global linking wait time bucket (2)", #"Regional NM & ACH inputs by tea (2)"}),
				    #"Removed Duplicates" = Table.Distinct(Source),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Date", type date}}),
				    #"Inserted Month Name" = Table.AddColumn(#"Changed Type", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Month Name", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Year", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Day Name", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Quarter",{{"Year", type text}, {"Quarter", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "Year Quarter", each "Q"&[Quarter]&"-"&[Year]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Quarter", Int64.Type}, {"Year", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "QuarterSort", each ([Year]*10)+[Quarter])
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

