{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Global DU escalations and escal\",\"Global DU wait time buckets\",\"Global linking escalations and\",\"Global linking wait time bucket\",\"Regional NM & ACH inputs by tea\",\"Regional NM & ACH outputs by te\",\"Global DU escalations and escal (2)\",\"Global DU wait time buckets (2)\",\"Global linking escalations and (2)\",\"Global linking wait time bucket (2)\",\"Regional NM & ACH inputs by tea (2)\",\"Regional NM & ACH outputs by te (2)\",\"DimDate\",\"AllMeasures\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Global DU escalations and escal (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Global DU escalations and escal\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "1e1491da-d8f9-43fd-a071-86bfafcb541e",
        "queryGroup": "DateExtract"
      },
      {
        "name": "Global DU wait time buckets (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Global DU wait time buckets\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "951b7729-eb35-4ccd-a757-f6f54f2b8a4c",
        "queryGroup": "DateExtract"
      },
      {
        "name": "Global linking escalations and (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Global linking escalations and\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "e634a944-6155-418e-8e47-34f770d8f128",
        "queryGroup": "DateExtract"
      },
      {
        "name": "Global linking wait time bucket (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Global linking wait time bucket\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "1700b591-725e-4dc1-ad46-04a11eb74f04",
        "queryGroup": "DateExtract"
      },
      {
        "name": "Regional NM & ACH inputs by tea (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Regional NM & ACH inputs by tea\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "01f167c1-db8f-4ffb-8155-efa59dedc94e",
        "queryGroup": "DateExtract"
      },
      {
        "name": "Regional NM & ACH outputs by te (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Regional NM & ACH outputs by te\",",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "a4e87ab7-3d7a-4bc3-826f-a418ffb20763",
        "queryGroup": "DateExtract"
      },
      {
        "name": "Global linking escalations and",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\LENOVO\\Desktop\\BI CLASS\\Pay Ops BI Lead Homework_Answer1.xlsx\"), null, true),",
          "    #\"Global linking escalations and _Sheet\" = Source{[Item=\"Global linking escalations and \",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Global linking escalations and _Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Action Created Parameter\", type date}, {\"No of Escalations\", Int64.Type}, {\"Escalation Rate\", type number}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Action Created Parameter\", \"Date\"}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Category\", each \"Global linking escalation\")",
          "in",
          "    #\"Added Custom\""
        ],
        "kind": "m",
        "lineageTag": "b43c9bb5-0b03-4ea3-b7b7-462ad150610f"
      },
      {
        "name": "Global linking wait time bucket",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\LENOVO\\Desktop\\BI CLASS\\Pay Ops BI Lead Homework_Answer1.xlsx\"), null, true),",
          "    #\"Global linking wait time bucket_Sheet\" = Source{[Item=\"Global linking wait time bucket\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Global linking wait time bucket_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Wait Hour Buckets\", type any}, {\"1. Within 1h\", type any}, {\"2. Within 2h\", type any}, {\"3. Within 4h\", type any}, {\"4. Within 8h\", type any}, {\"5. Within 12h\", type any}, {\"6. Within 24h\", type any}, {\"7. Within 48h\", type any}, {\"8. Within 72h\", type any}, {\"9. Over 72h\", type any}}),",
          "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",1),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Top Rows\",{{\"Wait Hour Buckets\", \"Date\"}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Renamed Columns\", {\"Date\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Wait Hour Buckets\"}, {\"Value\", \"Case Count\"}}),",
          "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Renamed Columns1\", {{\"Wait Hour Buckets\", each Text.AfterDelimiter(_, \". \"), type text}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Extracted Text After Delimiter\", \"Category\", each \"Global linking wait time bucket\")",
          "in",
          "    #\"Added Custom\""
        ],
        "kind": "m",
        "lineageTag": "f8833be4-e2b4-459b-846e-6db679c16fa2"
      },
      {
        "name": "Regional NM & ACH outputs by te",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\LENOVO\\Desktop\\BI CLASS\\Pay Ops BI Lead Homework_Answer1.xlsx\"), null, true),",
          "    #\"Regional NM & ACH outputs by te_Sheet\" = Source{[Item=\"Regional NM & ACH outputs by te\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Regional NM & ACH outputs by te_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Internal Action Actor Payops Team\", type any}, {\"APAC Expansion ops\", type any}, {\"APAC Mature ops\", type any}, {\"BRL ops\", type any}, {\"CEE ops\", type any}, {\"Central ops\", type any}, {\"CNO ops\", type any}, {\"Emerging ops\", type any}, {\"EUR ops\", type any}, {\"Europe & UK (Area)\", type any}, {\"Europe ops\", type any}, {\"GBP ops\", type any}, {\"GC ops\", type any}, {\"Global Processing Budapest 1\", type any}, {\"Global Processing Budapest 2\", type any}, {\"Global Processing Singapore 1\", type any}, {\"Global Processing Singapore 2\", type any}, {\"Global Processing Tallinn 1\", type any}, {\"Global Processing Tallinn 2\", type any}, {\"Global Processing Tallinn 3\", type any}, {\"Global Processing US 1\", type any}, {\"Global Processing US 2\", type any}, {\"JPYKRW ops\", type any}, {\"LatAm MEA ops\", type any}, {\"LatAm ops\", type any}, {\"NorthAm ops\", type any}, {\"Ops APAC - Global Processing\", type any}, {\"Pacific ops\", type any}, {\"ROSEA ops\", type any}, {\"SGDMYR ops\", type any}, {\"South Asia ops\", type any}, {\"SWIFT ops\", type any}, {\"Training\", type any}, {\"Column34\", type any}}),",
          "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",1),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Top Rows\",{{\"Internal Action Actor Payops Team\", \"Date\"}}),",
          "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Renamed Columns\", {\"Date\"}, \"Attribute\", \"Value\"),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Ops Team Currency\"}, {\"Value\", \"Output Count\"}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"Category\", each \"Regional NM &ACH outputs\"),",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom\",{{\"Output Count\", \"Queue Count\"}})",
          "in",
          "    #\"Renamed Columns2\""
        ],
        "kind": "m",
        "lineageTag": "426ec564-4995-48bd-b60a-1fa2501d8868"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "DateExtract"
      }
    ],
    "relationships": [
      {
        "name": "2b9b6238-c81e-4bdb-9f60-600f44efa720",
        "fromColumn": "Date",
        "fromTable": "DimDate",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c19b9ce6-a42c-4ba7-8d43-10025cc7d9c1"
      },
      {
        "name": "e8fcc3ed-6619-e28d-8f9e-13f775d6f216",
        "fromColumn": "Date",
        "fromTable": "Regional NM & ACH inputs by tea",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "2224c56c-d740-f4d8-2dfe-b882001fa1af",
        "fromColumn": "Date",
        "fromTable": "Global DU wait time buckets",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "2e9a3e46-01a2-c83a-a979-d21000bab2d6",
        "fromColumn": "Date",
        "fromTable": "Global DU escalations and escal",
        "toColumn": "Date",
        "toTable": "DimDate"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Global DU escalations and escal",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c7ff6b6b-b8ee-404f-80f5-566f0a07085c",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "No of Escalations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a1186b5-bae5-4a48-93c9-85337db5bf0c",
            "sourceColumn": "No of Escalations",
            "summarizeBy": "sum"
          },
          {
            "name": "Escalation Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0a75d6a-db45-4c0c-aa7e-e562da03f6eb",
            "sourceColumn": "Escalation Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc4b5804-efcc-4525-92ad-9d8b961fcf26",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dfc1c05b-ed65-46d2-8983-1b1a0150703d",
        "measures": [
          {
            "name": "AverageEscalationRate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('Global DU escalations and escal'[Escalation Rate])",
            "lineageTag": "d5313023-ba96-49ec-8afc-00b7d57d2f9b"
          },
          {
            "name": "GlobalDUEscalations",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK(CALCULATE([AverageEscalationRate],'Global DU escalations and escal'[Category]=\"Global DU escalations\")),0,CALCULATE([AverageEscalationRate],'Global DU escalations and escal'[Category]=\"Global DU escalations\"))",
            "lineageTag": "658797ed-3ed3-414c-9887-190aa26ad628"
          },
          {
            "name": "GloballinkingEscalations",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK(CALCULATE([AverageEscalationRate],'Global DU escalations and escal'[Category]=\"Global linking escalation\")),0,CALCULATE([AverageEscalationRate],'Global DU escalations and escal'[Category]=\"Global linking escalation\"))",
            "lineageTag": "297dd685-e94f-4885-8638-b3e95237fd1d"
          }
        ],
        "partitions": [
          {
            "name": "Global DU escalations and escal",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\LENOVO\\Desktop\\BI CLASS\\Pay Ops BI Lead Homework_Answer1.xlsx\"), null, true),",
                "    #\"Global DU escalations and escal_Sheet\" = Source{[Item=\"Global DU escalations and escal\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Global DU escalations and escal_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Action Created Parameter\", type date}, {\"No of Escalations\", Int64.Type}, {\"Escalation Rate\", type number}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Action Created Parameter\", \"Date\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Category\", each \"Global DU escalations\"),",
                "    #\"Appended Query\" = Table.Combine({#\"Added Custom\", #\"Global linking escalations and\"})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ec05cbf6-4574-4eed-a578-edf6e45212f3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b95202bc-747e-4e13-b127-1d151ee18e34",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b3796dc9-b2e1-4171-aa06-f956d32e2359",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4186e0c6-9fef-43f3-8e11-6e682b34a761",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "45c21d48-b373-4b87-a667-02202036a41a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8334b974-209d-4678-b2be-78956735b38f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3fe2b45e-0471-4230-9356-f296bb969c41",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0e56f338-bde2-4a6e-a54f-11f4cbaae6a6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "93af45bd-58f4-4f75-99dd-75794f63c947",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "341155ec-76e4-4ece-9d2e-f673f1be948f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5df9dfc2-c414-474a-a77c-e9cb4c66035a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "040b8211-fece-41fc-b7ee-36c98e302972",
                "ordinal": 3
              }
            ],
            "lineageTag": "db5e4120-7ce7-4f7c-90b0-59f54486b49c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0620dec7-64c8-4dea-a68a-c44bd30ea1b2",
        "partitions": [
          {
            "name": "DateTableTemplate_ec05cbf6-4574-4eed-a578-edf6e45212f3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Global DU wait time buckets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "55f00adc-b98c-4928-8cf5-f21974082d1d",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Wait Hour Buckets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5a3c4c-b01e-4b30-b631-4e0bcf87b5a3",
            "sourceColumn": "Wait Hour Buckets",
            "summarizeBy": "none"
          },
          {
            "name": "Case Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82a71742-d6aa-468b-a4bf-b74be3de7e72",
            "sourceColumn": "Case Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e73171c-fd44-4d77-ba9e-700495657e53",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b33b27a3-e2ab-4058-80af-220b7919d603",
        "measures": [
          {
            "name": "TotalCaseCount",
            "expression": "sum('Global DU wait time buckets'[Case Count])",
            "formatString": "#,0",
            "lineageTag": "820decad-7fa2-4d08-ae3f-b3c418b99721"
          },
          {
            "name": "Global linking TotalCaseCount",
            "expression": "IF(ISBLANK(CALCULATE([TotalCaseCount],'Global DU wait time buckets'[Category]=\"Global linking wait time bucket\")),0,CALCULATE([TotalCaseCount],'Global DU wait time buckets'[Category]=\"Global linking wait time bucket\"))",
            "formatString": "#,0",
            "lineageTag": "a8f6e899-144a-4e8a-b10c-b799d1847a93"
          },
          {
            "name": "Global DU TotalCaseCount",
            "expression": "IF(ISBLANK(CALCULATE([TotalCaseCount],'Global DU wait time buckets'[Category]=\"Global DU wait time bucket\")),0,CALCULATE([TotalCaseCount],'Global DU wait time buckets'[Category]=\"Global DU wait time bucket\"))",
            "formatString": "#,0",
            "lineageTag": "8b98a448-2583-44a6-a7a6-c7dac454a2de"
          }
        ],
        "partitions": [
          {
            "name": "Global DU wait time buckets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\LENOVO\\Desktop\\BI CLASS\\Pay Ops BI Lead Homework_Answer1.xlsx\"), null, true),",
                "    #\"Global DU wait time buckets_Sheet\" = Source{[Item=\"Global DU wait time buckets\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Global DU wait time buckets_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Wait Hour Buckets\", type any}, {\"1. Within 1h\", type any}, {\"2. Within 2h\", type any}, {\"3. Within 4h\", type any}, {\"4. Within 8h\", type any}, {\"5. Within 12h\", type any}, {\"6. Within 24h\", type any}, {\"7. Within 48h\", type any}, {\"8. Within 72h\", type any}}),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",1),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Top Rows\",{{\"Wait Hour Buckets\", \"Date\"}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Renamed Columns\", {\"Date\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Wait Hour Buckets\"}, {\"Value\", \"Ticket Count\"}}),",
                "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Renamed Columns1\", {{\"Wait Hour Buckets\", each Text.AfterDelimiter(_, \". \"), type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Extracted Text After Delimiter\", \"Category\", each \"Global DU wait time bucket\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom\",{{\"Ticket Count\", \"Case Count\"}}),",
                "    #\"Appended Query\" = Table.Combine({#\"Renamed Columns2\", #\"Global linking wait time bucket\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Appended Query\",{{\"Case Count\", Int64.Type}, {\"Date\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Regional NM & ACH inputs by tea",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "20ec094a-67dc-4efd-ab1e-e75c4f9b5470",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Ops Team Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c5634b4-29d1-44b1-b426-618e63db3861",
            "sourceColumn": "Ops Team Currency",
            "summarizeBy": "none"
          },
          {
            "name": "Queue Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82282884-834a-4b3f-9944-7fe8a496a455",
            "sourceColumn": "Queue Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c609491-f21f-497d-a2ab-96c316a5a830",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6f1c552-07b6-42b6-adbe-2b4241024a6a",
        "partitions": [
          {
            "name": "Regional NM & ACH inputs by tea",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\LENOVO\\Desktop\\BI CLASS\\Pay Ops BI Lead Homework_Answer1.xlsx\"), null, true),",
                "    #\"Regional NM & ACH inputs by tea_Sheet\" = Source{[Item=\"Regional NM & ACH inputs by tea\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Regional NM & ACH inputs by tea_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Ops Team Currency\", type any}, {\"APAC Expansion ops\", type any}, {\"APAC Mature ops\", type any}, {\"Emerging ops\", type any}, {\"EUR ops\", type any}, {\"Europe ops\", type any}, {\"GBP ops\", type any}, {\"JPYKRW ops\", type any}, {\"NorthAm ops\", type any}}),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",1),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Top Rows\",{{\"Ops Team Currency\", \"Date\"}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Renamed Columns\", {\"Date\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Ops Team Currency\"}, {\"Value\", \"Queue Count\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"Category\", each \"Regional NM & ACH inputs\"),",
                "    #\"Appended Query\" = Table.Combine({#\"Added Custom\", #\"Regional NM & ACH outputs by te\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Appended Query\",{{\"Queue Count\", Int64.Type}, {\"Date\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "34755d2e-f059-4f19-9d40-0baa6ac79472",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c19b9ce6-a42c-4ba7-8d43-10025cc7d9c1"
                },
                "isDefault": true,
                "relationship": "2b9b6238-c81e-4bdb-9f60-600f44efa720"
              }
            ]
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "13a54d02-4c44-44c5-a9ad-7d9962389a1c",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95ff0f46-fa9e-4148-953c-4c61074f31ee",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e92c0e40-7f22-4657-a2d6-21d07500d151",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b960a9d-e8f3-4584-873e-4921ca8bb6f0",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d335c929-1227-4665-8394-f9d8c4d5d10c",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f660785c-6fe6-4c54-a3ae-3ed2d04c2cea",
            "sortByColumn": "QuarterSort",
            "sourceColumn": "Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afb14f03-17f6-4193-9bb5-0922f272ada7",
            "sourceColumn": "QuarterSort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90779531-e4d0-4e14-8cb9-11a8f2404263",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({#\"Regional NM & ACH outputs by te (2)\", #\"Global DU escalations and escal (2)\", #\"Global DU wait time buckets (2)\", #\"Global linking escalations and (2)\", #\"Global linking wait time bucket (2)\", #\"Regional NM & ACH inputs by tea (2)\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(Source),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Duplicates\",{{\"Date\", type date}}),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Changed Type\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Month Name\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Year\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Day Name\", \"Month\", each Date.Month([Date]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month\", \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Inserted Quarter\",{{\"Year\", type text}, {\"Quarter\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type1\", \"Year Quarter\", each \"Q\"&[Quarter]&\"-\"&[Year]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Quarter\", Int64.Type}, {\"Year\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"QuarterSort\", each ([Year]*10)+[Quarter])",
                "in",
                "    #\"Added Custom1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c19b9ce6-a42c-4ba7-8d43-10025cc7d9c1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9cc2006e-63dc-43de-9798-218f467dd28f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c5482c8c-abba-4bc1-b148-160094806351",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1fbefd2f-78a7-4efa-aa3a-009c3de34736",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "140befc0-3069-4dc7-a304-f3bfd1b12a69",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9659604-086c-41e7-a961-471701a67efc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ba1ca26a-ab9a-40f9-9bc0-5e5cdbe3ef41",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a39c7ad9-2d02-44e4-99cf-9c12ecbd9d5d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6b9cdcd3-4e41-4c19-8778-742c1abea192",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1105fca7-efcd-4c72-a88e-a90dd94fd360",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "57a96559-e5ae-4110-baf2-051530a24849",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "de1ee83c-9f80-4cf3-adf9-6665c2444361",
                "ordinal": 3
              }
            ],
            "lineageTag": "625e7c85-075a-417a-a83b-ab8c440a99d0"
          }
        ],
        "isHidden": true,
        "lineageTag": "f7adf2f0-95dc-4741-9bbb-3f277e71823c",
        "partitions": [
          {
            "name": "LocalDateTable_c19b9ce6-a42c-4ba7-8d43-10025cc7d9c1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimDate'[Date])), 1, 1), Date(Year(MAX('DimDate'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "AllMeasures",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7dbffbf-b458-4b1a-8495-d2a98c844040",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "773e6eb7-9aa2-4072-82c3-86c5164a5047",
        "partitions": [
          {
            "name": "AllMeasures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}